export type Exercise = {
  id: string;
  name: string;
  muscleGroups: string[];
  primaryMuscle: string;
  secondaryMuscles: string[];
  equipment: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  movementType: string;
  instructions: string[];
  safety: string;
};

/** Original descriptions. Not copied from a licensed video library. */
export const exercises: Exercise[] = [
  {
    id: "squat",
    name: "Squat",
    muscleGroups: ["legs"],
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes", "core"],
    equipment: "bodyweight",
    difficulty: "beginner",
    movementType: "squat",
    instructions: ["Stand with feet about shoulder-width apart.", "Sit your hips back and bend your knees.", "Keep your chest up and stand again."],
    safety: "Stop if your knees move into a sharp pain. Keep the heels down.",
  },
  {
    id: "hinge",
    name: "Hip hinge",
    muscleGroups: ["posterior"],
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "back"],
    equipment: "bodyweight",
    difficulty: "beginner",
    movementType: "hinge",
    instructions: ["Soften your knees.", "Push your hips back until your torso leans forward.", "Stand by driving the hips forward."],
    safety: "Keep a long spine. Do not round hard to chase range.",
  },
  {
    id: "pushup",
    name: "Push-up",
    muscleGroups: ["push"],
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bodyweight",
    difficulty: "beginner",
    movementType: "push",
    instructions: ["Hands under your shoulders.", "Lower your chest between your hands.", "Press the floor away to return."],
    safety: "Use an incline if the full range pulls your lower back into a sag.",
  },
  {
    id: "row",
    name: "Bent-over row",
    muscleGroups: ["pull"],
    primaryMuscle: "upper back",
    secondaryMuscles: ["biceps", "rear shoulders"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    movementType: "pull",
    instructions: ["Hinge until your torso is stable.", "Pull the weights toward your ribs.", "Lower them without jerking."],
    safety: "Brace before the pull. Do not yank with the lower back.",
  },
  {
    id: "lunge",
    name: "Split squat",
    muscleGroups: ["legs"],
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["glutes"],
    equipment: "bodyweight",
    difficulty: "beginner",
    movementType: "lunge",
    instructions: ["Step one foot back.", "Lower the back knee toward the floor.", "Press through the front foot to stand."],
    safety: "Use a shorter stance if balance is the limiter.",
  },
  {
    id: "plank",
    name: "Plank",
    muscleGroups: ["core"],
    primaryMuscle: "core",
    secondaryMuscles: ["shoulders"],
    equipment: "bodyweight",
    difficulty: "beginner",
    movementType: "brace",
    instructions: ["Forearms or hands on the floor.", "Make a straight line from head to heels.", "Breathe while you hold."],
    safety: "End the hold if the lower back starts to pinch.",
  },
  {
    id: "deadbug",
    name: "Dead bug",
    muscleGroups: ["core"],
    primaryMuscle: "core",
    secondaryMuscles: ["hips"],
    equipment: "bodyweight",
    difficulty: "beginner",
    movementType: "control",
    instructions: ["Lie on your back with arms up and knees bent.", "Reach one arm and the opposite leg away.", "Return and switch sides."],
    safety: "Keep the lower back quiet on the floor.",
  },
  {
    id: "carry",
    name: "Suitcase carry",
    muscleGroups: ["core"],
    primaryMuscle: "core",
    secondaryMuscles: ["grip", "shoulders"],
    equipment: "dumbbell",
    difficulty: "beginner",
    movementType: "carry",
    instructions: ["Hold one weight at your side.", "Walk tall without leaning.", "Switch hands and walk back."],
    safety: "Choose a weight you can keep level.",
  },
  {
    id: "hip-bridge",
    name: "Hip bridge",
    muscleGroups: ["posterior"],
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: "bodyweight",
    difficulty: "beginner",
    movementType: "bridge",
    instructions: ["Lie down with feet flat.", "Press the hips up until the body is a line.", "Lower with control."],
    safety: "Do not shove the ribs up at the top.",
  },
  {
    id: "shoulder-press",
    name: "Shoulder press",
    muscleGroups: ["push"],
    primaryMuscle: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    movementType: "press",
    instructions: ["Weights at shoulder height.", "Press them overhead.", "Lower to the shoulders."],
    safety: "Stop if the shoulder pinches at the top. A neutral grip is fine.",
  },
  {
    id: "walk",
    name: "Brisk walk",
    muscleGroups: ["cardio"],
    primaryMuscle: "legs",
    secondaryMuscles: ["cardio"],
    equipment: "none",
    difficulty: "beginner",
    movementType: "cardio",
    instructions: ["Walk at a pace you can speak in short sentences.", "Keep the steps quiet.", "Finish while you still feel steady."],
    safety: "Use the activity recorder if you want a route.",
  },
  {
    id: "breath-reset",
    name: "Easy breathing reset",
    muscleGroups: ["mobility"],
    primaryMuscle: "breathing",
    secondaryMuscles: ["core"],
    equipment: "none",
    difficulty: "beginner",
    movementType: "mobility",
    instructions: ["Sit or lie down.", "Inhale through the nose for about four seconds.", "Exhale longer than you inhaled."],
    safety: "Stop if you feel lightheaded and breathe normally.",
  },
];
